port: '/dev/ttyUSB3' # communication port
eq_preset: false # [Equilibrium/Preset] -> True , [P1/P2/PL] -> False
hand_perc: false # [Hand command in percentual] -> True , [Hand command in TICK] -> False
current: false # [Activate current reader] -> True, [Deactivate current reader] -> False
unit: 'TICK' # Unit of measurement, ['DEG', 'RAD', 'TICK']
step_time: 0.0025 # Step time
baudrate: 2000000 # BaudRate [200000, 460800]
IDcubes: [33] # ID cubes in chain
IDhands: [] # ID hands in chain
